# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build postgres-candy-api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t postgres-candy-api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system postgres-candy-api && \
          adduser --system -G postgres-candy-api postgres-candy-api

COPY dist/postgres-candy-api postgres-candy-api
RUN chown -R postgres-candy-api:postgres-candy-api .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix postgres-candy-api --omit=dev -f install

CMD [ "node", "postgres-candy-api" ]
